### ISSUE TITLE
Use colorama for a nice interface

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#103]

**Comment by nemaniarjun** [comment]
Closing, deprecating CLI

**Comment by abhsag24** [comment]
Are we sure about deprecating CLI? It was just an idea it would only happen
if you guys agree :P

**Comment by nemaniarjun** [comment]
I think you were right about it being a lot of work.
We will still keep `UIP --service` which IMO is more useful then the CLI
