### ISSUE TITLE
Add option for not connecting to the internet 

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#11]
i think it would cool if we could add an option for not connecting to the internet and changing the wallpapers directly from the directory, all the functionality is there we just need to add an option

**Comment by hasan356** [comment]
in which file we need to add an option

**Comment by DarkSouL11** [comment]
@abhsag24 Do you want the user to specify from which directory the wallpapers a applied or use the default one which you've specified.

**Comment by abhsag24** [comment]
@hasan356 The option would be from `scheduler.py` There's a call to `initFetch` which calls `get_images` which connects to the internet. It'd be awesome if that call is optional.

**Comment by abhsag24** [comment]
@DarkSouL11 for this issue it'd be the default one. We do have an issue for giving the user option to change the folder, see https://github.com/NIT-dgp/UIP/issues/27
