### ISSUE TITLE
Need GUI

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#112]
i think UIP is stable enough, especially after --flush, to have a GUI

**Comment by nkprince007** [comment]
This takes it way beyond, I guess. But don't know if we could make it cross-platform.

**Comment by abhsag24** [comment]
@nkprince007 we could use qt or gtk those are already cross-platform right? we cant make native ui's sadly :(

**Comment by nkprince007** [comment]
What do we use Tkinter or PyQt? I'd recommend PyQt, bro. Since I've had a small experience with Qt-C++ variant.

**Comment by abhsag24** [comment]
i'm all for PyQt :P depends on the implementer

**Comment by nemaniarjun** [comment]
Close this? New GUI features are added to as new issues anyways.
