### ISSUE TITLE
add flag to set UIP pics directory

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#113]
currently it creates directory in folder where UIP is called from

**Comment by nkprince007** [comment]
But, I think it's better if we add a flag specifying where to download them to.. what'd you say @abhsag24

**Comment by abhsag24** [comment]
@nkprince007 yes and if that isn't specified store them in temp

**Comment by DarkSouL11** [comment]
@abhsag24 don't you think it's better to have the default download location as the standard pictures directory of the OS.

**Comment by abhsag24** [comment]
@DarkSouL11 i'm not sure about standard pics folder but im all for a default folder

**Comment by lohani2280** [comment]
@abhsag24 i want to work on this issue . Do i need to add a flag specifying  where to download them to??.....any more suggestions which u wanna give??

**Comment by nkprince007** [comment]
I don't think this issue is relevant any more since we opened up to GUI and the cli section is no longer relevant. Better closing it.
