### ISSUE TITLE
Iterate pictures folder present in system

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#119]
This is a standard feature, which I don't think UIP implements yet. 
To randomly select and change wallpapers from a given folder.
REMINDER: Flush should be turned off if this is selected.

**Comment by abhsag24** [comment]
flush doesn't work until you specify it to :D

**Comment by nemaniarjun** [comment]
Uhmm... Favs solves this?

**Comment by nemaniarjun** [comment]
Closed by issue #318
