### ISSUE TITLE
Option for different URL's other than reddit

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#12]
i think UIP should be able to extract images of a considerable resolution from any website

**Comment by nkprince007** [comment]
I would recommend [this](unsplash.com) bro

**Comment by nkprince007** [comment]
It provides an API too..

**Comment by Aniq55** [comment]
I think [QuoteFancy](https://quotefancy.com) would be a great place to take pics from. But they also have a page in [Reddit](https://www.reddit.com/r/Quotefancy/)

**Comment by nemaniarjun** [comment]
Duplicate of #162
