### ISSUE TITLE
Option to save favourites

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#121]
Some wallpapers are better than the other. 
I would like an option to save the present wallpaper into some local folder by which it is immune to --flush

**Comment by nkprince007** [comment]
This seems really cool.

**Comment by Aniq55** [comment]
Wouldnt it be better if this is implemented in the GUI version?

**Comment by abhsag24** [comment]
i dont think we should wait, this should be absolutely necessary after https://github.com/NIT-dgp/UIP/issues/120 , which i think is going to be the next big thing :P
