### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by DarkSouL11** [NIT-dgp/UIP#128]
The present script uses all the CPU available which is not obviously good. Make the required changes so that it doesn't use much of CPU.

![screenshot from 2016-11-21 10-42-45](https://cloud.githubusercontent.com/assets/8626394/20473977/fd393422-afe9-11e6-811a-63c75d4732f7.png)

**Comment by Aniq55** [comment]
I've limited CPU usage to roughly 33%, will that be okay?
