### ISSUE TITLE
Add detailed instructions to install coala in README.md

### ISSUE THREAD

**Issue by DarkSouL11** [NIT-dgp/UIP#135]
UIP uses coala for linting.The present "how to contribute" section has instructions to install coala, however those instructions are not sufficient and users have ended up installing pip and coala on python 2.Coala works only with python 3, so update readme with instructions to install pip and coala for python3.

To install pip for python3 use `apt-get install python3-pip`.
for coala: `pip3 install coala`
add suitable instructions along with above commands and update readme file.

**Comment by abhsag24** [comment]
closed after we moved to `test-requirements.txt`
