### ISSUE TITLE
UIP not downloading images 

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#138]
its happening since yesterday im not sure if its my internet?  can anyone reproduce?

**Comment by DarkSouL11** [comment]
Same thing happens with me too, Internet is not the reason tested it using my mobile data also.

**Comment by abhsag24** [comment]
i'll investigate today

**Comment by nkprince007** [comment]
I checked out to `14d0ff5` and tried downloading, still no luck.
