### ISSUE TITLE
Unable to change wallpapers due to root access issue

### ISSUE THREAD

**Issue by akshatnitd** [NIT-dgp/UIP#142]
```.uip``` needs root access to download images into it. Also even if called using sudo it does download images but is unable to change the wallpaper . So, we need to change the directory location.

**Comment by nemaniarjun** [comment]
Change the default folder from `~/.uip` to `~/uip-pics` or similar

**Comment by hackrush01** [comment]
It is still not working without sudo command. I have checked the program in a debian flavor.

**Comment by abhsag24** [comment]
@hackrush01 can you post a tracback? it might be an issue specific to you?

**Comment by hackrush01** [comment]
It is not an error of that sort. Everything is working fine. it even displays changing wallpaper but doesn't change it.

**Comment by abhsag24** [comment]
can you open a new issue regarding this? please add which how you installed UIP, and what OS you are running?

**Comment by hackrush01** [comment]
I already have a fix. Does it need a new issue?

**Comment by hackrush01** [comment]
I already have a fix. Does it need a new issue?

**Comment by abhsag24** [comment]
@hackrush01 i'm not sure that fix changes anything cause we have 777 permissions on all folders. We need to get to the source of the problem before applying random fixes right? and if we then find your fix the best solution we merge that?

**Comment by abhsag24** [comment]
FWIW i have Ubuntu 16.04 and it worksperfectly for me

**Comment by hackrush01** [comment]
Looks like it is fixed. I reinstalled using setup.py install and it worked. Earlier it created the ```.uip``` directory in the ```/root``` folder. This time it created it in the home folder.

**Comment by abhsag24** [comment]
pip version is broken for ubuntu i'll do a new release once: #187 and #185 are merged

**Comment by hackrush01** [comment]
I didn't do a pip install. And I was using Kali Rolling 2016.2.
