### ISSUE TITLE
Use unsplash API

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#144]
we use their css classes for scraping it'd be awesome if we could use their API

**Comment by akshatnitd** [comment]
@abhsag24 Could we use ```https://source.unsplash.com/random``` to download random images from unsplash ? Or else, we can get a json from ```https://unsplash.it/list```? The only problem with the latter is that it return the same json everytime!

**Comment by akshatnitd** [comment]
@abhsag24 If we do this part first, then issue #165 can be solved at once!

**Comment by abhsag24** [comment]
@akshatnitd are u sure https://unsplash.it/list returns the same list? it would be updated in some time right?

**Comment by abhsag24** [comment]
https://source.unsplash.com/random is also good if u can extract multiple links

**Comment by akshatnitd** [comment]
@abhsag24 It returns the json the same list... And also https://unsplash.it isn't the ofiifcial API for unsplash.

**Comment by abhsag24** [comment]
i think this should be a step in the direction of: https://github.com/NIT-dgp/UIP/issues/120 like we download 4-5 wallpapers every time a wallpepr is changed it gets deleted and a new one gets downloaded

**Comment by akshatnitd** [comment]
@abhsag24 We could also randomly select links from the json. In this way, the entire code structure would be uniform for reddit and unsplash. What say?

**Comment by abhsag24** [comment]
@akshatnitd  but you said itsnt update right?

**Comment by akshatnitd** [comment]
@abhsag24 Yes, it already has around 1100 pics I guess... So, would it be the right way? Or else we need to work on extracting multiple links

**Comment by abhsag24** [comment]
@akshatnitd I guess our present structure is better than both the cases right? I think let's stick to that till we find a better Alternative, and you can just add tests for that :P

**Comment by akshatnitd** [comment]
@abhsag24 Yes, will do that :+1:

**Comment by nkprince007** [comment]
I think it's already been implemented. 😉
