### ISSUE TITLE
make settings.json pretty

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#158]
right now its just one line format it into multiple lines

**Comment by nkprince007** [comment]
I think this is done already.. :P

**Comment by abhsag24** [comment]
@nkprince007 wen setings.json is updated from gui then it prettifies

**Comment by nkprince007** [comment]
Oh, that.. :stuck_out_tongue:

**Comment by DanRadulescu962** [comment]
Can I be assigned?

**Comment by abhsag24** [comment]
Ahh sorry this is not how this works, on our repo you clailm an issue by
commenting on it :D
