### ISSUE TITLE
Add gitter link to the README.md

### ISSUE THREAD

**Issue by PaliwalSparsh** [NIT-dgp/UIP#17]
Add link to [#general](https://gitter.im/NIT-dgp/General) ( https://gitter.im/NIT-dgp/General ) channel in the README.md so that reaching to the maintainers is easy for newcomers.

**Comment by abhsag24** [comment]
It should go under the heading Contact Us

**Comment by PaliwalSparsh** [comment]
I don't think this is to be done by a newcomer rather be done before newcomers come. How to contact us should be fixed asap and done by us only.

**Comment by abhsag24** [comment]
until its done it's difficulty is for a newcomer, i'll add it before we go public. Just in case a newcomer drops by early he'll have another task to do :)

**Comment by hasan356** [comment]
i am working on it

**Comment by abhsag24** [comment]
@hasan356  awesome :D feel free to ping us here, or gitter if you need any help

**Comment by abhsag24** [comment]
issue closed with: https://github.com/NIT-dgp/UIP/pull/3

@hasan356  should i suggest another issue?

**Comment by hasan356** [comment]
Yes please suggest

**Comment by abhsag24** [comment]
how about https://github.com/NIT-dgp/UIP/issues/18
