### ISSUE TITLE
Complete tests for scrape.py

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#170]
tests for scrape.py dont hit all target lines for eg:  https://codecov.io/gh/NIT-dgp/UIP/src/1dccfdd36dcc37468d8007b157b9c97d3164485a/uiplib/scrape.py
contains lines where tests dont hit. it'll be best if we can add tests for those lines.

**Comment by nkprince007** [comment]
Being addressed in #8.
