### ISSUE TITLE
Add newcomer guide to Readme

### ISSUE THREAD

**Issue by nemaniarjun** [NIT-dgp/UIP#173]
In readme, `How to contribute` can contain a link to coala's newcomer guide. 
Just because its extremely helpful.

http://docs.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by abhsag24** [comment]
Add it as a note in the How to Contribute Section like: `Note: If you're an absolute newcomer [this guide](<link to guide>) might help you out. Though keep in mind some of the standards are different.`

**Comment by rahul-kumi** [comment]
@nemaniarjun, are you working on it, if not can I be assigned?

**Comment by DanRadulescu962** [comment]
Hi,I
 would like to work at this issue.

**Comment by abhsag24** [comment]
@DanRadulescu962 awesome! feel free to reach us on our [gitter channel](https://gitter.im/NIT-dgp/General) if you need any help

**Comment by abhsag24** [comment]
@DanRadulescu962 also the link in the issue is expired you might want to replace it with: `http://felixrieseberg.com/open-source-newcomers/` this is not the coala guide but a random blog which is awesome :D

**Comment by abhsag24** [comment]
you may also add `https://docs.coala.io/en/release-0.6/Getting_Involved/Newcomers.html` and  `https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud` you can say something like:
```
>Note: If you're an absolute newcomer these sources might help you out. Though keep in mind some of the standards are different.

<url 1>
<url 2>
<url 3>
```
