### ISSUE TITLE
No proxy support for UIP users

### ISSUE THREAD

**Issue by Diptanshu8** [NIT-dgp/UIP#178]
For all the users who are using behind UIP from behind a proxy network, requests module used in scrape.py needs to be specified with a proxy configuration. This feature is not available.
There are multiple ways to do so:
1. Either we add params to the argparse while running UIP
2. We create a configuration file specifying the proxies. Then we add a tutorial for writing a config file for the user in the README. (Many orgs support this way)

**Comment by Diptanshu8** [comment]
I would be working on the second option as of now to get the proxy settings up and working.

**Comment by abhsag24** [comment]
@Diptanshu8  see `settings.json` in `/home/<user>/.uip/settings.json`

**Comment by abhsag24** [comment]
and also see settings.py

**Comment by abhsag24** [comment]
@Diptanshu8 did you get around to doing this?
