### ISSUE TITLE
Specify the parser for better output

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#18]
/usr/lib/python3/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 4 of the file UIP.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

**Comment by abhsag24** [comment]
Change https://github.com/NIT-dgp/UIP/blob/master/scrape.py#L15
from 
`BeautfulSoup(html)`
to
`BeautifulSoup(html, "html.parser")`
