### ISSUE TITLE
create a Printer class

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#194]
which has `Normal DEBUG and WARNING` args'
and we should display everything with the print class, including errors and information messages.

**Comment by abhsag24** [comment]
or we could also use PyPrint

**Comment by abhsag24** [comment]
closing this as wont fix CC @nkprince007 open this if it seems necessary? closing this for focus on GUI

**Comment by nkprince007** [comment]
Admit it, CLI will be deprecated, in future applications, probably a --verbose tag should be added for DEBUGGING uses.
