### ISSUE TITLE
GUI not starting.

### ISSUE THREAD

**Issue by hackrush01** [NIT-dgp/UIP#200]
If run with ```UIP --ui``` it produces the following message.

![uip ui error](https://cloud.githubusercontent.com/assets/17583974/20987820/1b2c8e5e-bcf4-11e6-9954-68334425b87b.jpg)

**Comment by abhsag24** [comment]
@hackrush01 yes you need to download imagetk for your OS it isnt packaged with UIP

**Comment by abhsag24** [comment]
opened this for you. https://github.com/NIT-dgp/UIP/issues/201
