### ISSUE TITLE
Readme: Add instructions for GUI in Run

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#201]
add that you need to install Imagetk on your os, and to run u need to do `UIP --ui`

**Comment by hackrush01** [comment]
Are you using PIL for python3? Is it available?

**Comment by nkprince007** [comment]
No, PIL is deprecated, Pillow is under maintainence. @hackrush01

**Comment by hackrush01** [comment]
What should I use then?

**Comment by nkprince007** [comment]
Use Pillow as specified in `requirements.txt`

**Comment by hackrush01** [comment]
I already have it!
![screenshot from 2016-12-08 18-50-51](https://cloud.githubusercontent.com/assets/17583974/21011448/535c9b06-bd77-11e6-9b27-eee8674ef0d2.png)

**Comment by abhsag24** [comment]
@hackrush01 use sudo apt-get install python3-pil.imagetk if you're on an ubuntu machine

**Comment by hackrush01** [comment]
Yes this worked, thank you. Updating the README.md now.

**Comment by abhsag24** [comment]
hey so it'd be better if this is changed to 
```
If you want to try out our Experimental GUI feature:
use: `UIP --ui`

to install requirements for this feature, run:
`pip install -r gui-requirements.txt`

For some OS' you might need to install Imagetk seperately
for eg: in Ubuntu you can install it by:
`sudo apt-get install python3-pil.imagetk`
```
