### ISSUE TITLE
setup.py requires uninstalled packages

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#216]
happens because in `utils.py` we have `OnlineFetch`, which connects to the main code which has dependencies, and we require `utils.py` in the setup file.
Move Online Fetch to a new `OnlineFetch.py` file

**Comment by nkprince007** [comment]
I'll work on this tonight.

**Comment by hackrush01** [comment]
How to reproduce the error?

**Comment by abhsag24** [comment]
@hackrush01 remove all requirements, uninstall UIP then run`python3 setup.py install`
