### ISSUE TITLE
Add utils folder, differentiate, setup-utils, and regular utils

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#224]
right now setup requires functions from `utils` but breaks everytime we connect it to the main code. It'd be best if we could differentiate utils into `setup-utils` and `uip-utils`

**Comment by hackrush01** [comment]
> right now setup requires functions from `utils` but breaks everytime we connect it to the main code. It'd be best if we could differentiate utils into `setup-utils` and `uip-utils`

"breaks everytime we connect it to main code" means? What breaks? What connects to main code?"

**Comment by abhsag24** [comment]
whenever we try to import other modules like `scrape` or `scheduler`
