### ISSUE TITLE
Do not allow --service start and --ui together

### ISSUE THREAD

**Issue by nemaniarjun** [NIT-dgp/UIP#225]
Creats a PID-file that doesn't run, 
Causing ProcessLookupError in exit_UIP()

**Comment by nemaniarjun** [comment]
Alternatively, handle ProcessLookupError in exit_UIP(), using os.remove(pid-file)

**Comment by nkprince007** [comment]
Could you work on this and give a quick fix @nemaniarjun?

**Comment by nemaniarjun** [comment]
Will do

**Comment by abhsag24** [comment]
@nemaniarjun a better issue would be to fix the case where this happens :P

**Comment by nemaniarjun** [comment]
did not get you @abhsag24 
You are talking about the first solution right?

**Comment by abhsag24** [comment]
ahh yes
