### ISSUE TITLE
Make GUI better.

### ISSUE THREAD

**Issue by hackrush01** [NIT-dgp/UIP#227]
Two things
1. The whole picture should fit the frame.
2. As a whole UI should be made to look better. Maybe use something other than tkinter before it's to late.

**Comment by nkprince007** [comment]
We'd have a lot of dependencies, like if you're onto building something with PyQt, you'd get an enriched UI, but, considering the scale of project and the memory footprint, it seems all the way good to have something that comes standard. But anyway, options are welcome.

**Comment by hackrush01** [comment]
But at-least the pictures should fit perfectly in the UIP frame.

**Comment by nkprince007** [comment]
But that doesn't mean we would have to change tkinter..
