### ISSUE TITLE
PEP8 errors in scheduler.py

### ISSUE THREAD

**Issue by ghoshbishakh** [NIT-dgp/UIP#23]
scheduler.py:1:5: E271 multiple spaces after keyword
scheduler.py:3:31: E231 missing whitespace after ','
scheduler.py:3:43: E231 missing whitespace after ','
scheduler.py:3:51: E231 missing whitespace after ','
scheduler.py:6:30: W291 trailing whitespace
scheduler.py:7:1: E302 expected 2 blank lines, found 0
scheduler.py:13:1: W293 blank line contains whitespace
scheduler.py:14:9: E265 block comment should start with '# '
scheduler.py:16:13: W291 trailing whitespace
scheduler.py:25:21: E225 missing whitespace around operator
scheduler.py:30:26: E225 missing whitespace around operator
scheduler.py:31:1: W293 blank line contains whitespace
scheduler.py:35:1: W293 blank line contains whitespace
scheduler.py:36:5: E303 too many blank lines (2)
scheduler.py:36:26: E231 missing whitespace after ','
scheduler.py:37:18: E225 missing whitespace around operator
scheduler.py:43:28: E225 missing whitespace around operator

**Comment by abhsag24** [comment]
closing in favor of https://github.com/NIT-dgp/UIP/issues/24
