### ISSUE TITLE
Make UIP website

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#253]
just a landing page detailing members and changelog and executables and how to use section , just like a Readme but a website :P

**Comment by Aniq55** [comment]
What about Github Pages?
https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3

**Comment by abhsag24** [comment]
yes github pages will do fine. Want me to create a repository?

**Comment by nkprince007** [comment]
I don't think a new one is necessary, bro. We already have UIP-misc of the job.

**Comment by nkprince007** [comment]
Is anyone working on this? If not, I'll take it up.

**Comment by nemaniarjun** [comment]
Go ahead bro. :) I would like to help you with it though. I want to learn web dev :P

**Comment by nemaniarjun** [comment]
http://jekyllthemes.org/themes/minimal-mistakes/

http://jekyllthemes.org/themes/new-age/

**Comment by nkprince007** [comment]
> Go ahead bro. :) I would like to help you with it though. I want to learn web dev :P

@nemaniarjun  I'll be sending in a PR to gh-pages with some screenshots once the theme is decided. Anyone interested could work on the PR to `gh-pages` branch. 

I prefer jekyll for the static site generation. Makes the publishing process a breeze.
And I think pretty much everyone loves to work on template based stuff.

**Comment by nkprince007** [comment]
[Jekyll](https://jekyllrb.com/) or [React](https://facebook.github.io/react/)

**Comment by abhsag24** [comment]
i personally like React but now i guess this is already an issue on the org website, so closing it here.
