### ISSUE TITLE
When downloading, create `pics` folder if it does not exist.

### ISSUE THREAD

**Issue by nemaniarjun** [NIT-dgp/UIP#260]
Steps to reproduce: 
1. Delete `.uip/pics`
2. run `UIP`

**Comment by abhsag24** [comment]
@nemaniarjun for a normal user why wouldn't it exist in the first place?

**Comment by Aniq55** [comment]
I don't understand this issue

**Comment by abhsag24** [comment]
I think our structure has changed since i created, kindly close :P
