### ISSUE TITLE
scheduler.py: Change classname to titlecase

### ISSUE THREAD

**Issue by nkprince007** [NIT-dgp/UIP#268]
Follow the [wiki](https://github.com/NIT-dgp/UIP/wiki) and make modifications accordingly.

- [ ] Rename the class `scheduler` to `Scheduler`
- [ ] Change the definitions in the class to match `snake_case`

**Comment by snehith57624** [comment]
Could I be assigned this?

**Comment by abhsag24** [comment]
@snehith57624 sure! :D in this repo we claim issues by commenting on it, which you already have! so  you can go ahead and start working on it  :D
