### ISSUE TITLE
Add configuration file for various settings

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#27]
Example TIMEOUT, number of images to download, when to delete, location of the pics folder etc.

**Comment by pandusonu2** [comment]
Basically, need to make a script which modifies 'constants.py' file

**Comment by abhsag24** [comment]
also settings as arguments would be good too, so i guess we have the issue in two parts, add settings.py, transfer some variables from constants.py into that file, and add support for command line arguments, both of these can be solved seperately.
