### ISSUE TITLE
GUI: Arrange the buttons (Set Wallpaper, Flush) side by side

### ISSUE THREAD

**Issue by Aniq55** [NIT-dgp/UIP#287]

**Comment by Aniq55** [comment]
Would it look nice, if instead of text, we use symbols for 
Set Wallpaper- Green Tick
Download - Blue Download Symbol
Flush - Red Cross

**Comment by nemaniarjun** [comment]
Instead of red cross we can use a trash icon and since we don't have a download button anymore, we use a `play` button for start and red cross for stop.

**Comment by nemaniarjun** [comment]
See #191

**Comment by Aniq55** [comment]
![screenshot from 2016-12-28 14-07-04](https://cloud.githubusercontent.com/assets/20151858/21517665/f2301ade-cd06-11e6-9a18-d8eb0e9e45d0.png)
Should I open a PR for this?
@nemaniarjun @abhsag24 @nkprince007 @DarkSouL11

**Comment by nemaniarjun** [comment]
Sure go ahead then we can close this issue and open a new one for the use of symbols instead of text. After #191 is done.

**Comment by nemaniarjun** [comment]
Start a PR.

**Comment by abhsag24** [comment]
looks Awesome @Aniq55
