### ISSUE TITLE
Make Flush work

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#290]
right now its just a stub it'll be great to have that functionality along with start

**Comment by Aniq55** [comment]
Flush means we will delete that image, right?

**Comment by abhsag24** [comment]
well intuitively right now it feels like it, though flush right now means delete all images and start downloading new images

**Comment by nemaniarjun** [comment]
I am working on this

**Comment by nemaniarjun** [comment]
Nearly done too
