### ISSUE TITLE
Flush images

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#30]
Once the set amount of images are downloaded, they keep on repeating and no new images are downloaded. 
This needs to change, as- the more the merrier.

**Comment by abhsag24** [comment]
related to https://github.com/NIT-dgp/UIP/issues/5

**Comment by abhsag24** [comment]
adding needs design because following facts need to be addressed from slack:
like for how long should we wait before

[1:38]  
deleting the pic and all that?

[1:38]  
what if a pic is shceduled to be deleted and it is the wallpaper at that moment

**Comment by abhsag24** [comment]
closed by @nkprince007 's PR
