### ISSUE TITLE
Add standalone Download button

### ISSUE THREAD

**Issue by nemaniarjun** [NIT-dgp/UIP#305]
Usefull after Flush, and on first run, to Download more/new wallpapers.

**Comment by abhsag24** [comment]
@nemaniarjun why not update UI after play is clicked?

**Comment by nemaniarjun** [comment]
That doesnt give the expected result I guess... `scheduler` changes the wallpapers, what if I only want new wallpapers?

**Comment by abhsag24** [comment]
@nemaniarjun do you think it'll be a valid issue after https://github.com/NIT-dgp/UIP/issues/120 ?

**Comment by nemaniarjun** [comment]
I am not sure. What about favourites issue?

**Comment by abhsag24** [comment]
@nemaniarjun what about favorites?

**Comment by nemaniarjun** [comment]
We don't want to delete favorite wallpapers?

**Comment by nemaniarjun** [comment]
Right?

**Comment by abhsag24** [comment]
yes

**Comment by abhsag24** [comment]
btw was thinking we'd store favorites in a different location

**Comment by abhsag24** [comment]
@nemaniarjun closing this as wontfix, reopen if you find this relevant
