### ISSUE TITLE
add support for bmp files 

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#32]
just add bmp to the list in scrape.py 
change from:
```
if link['href'].endswith(('jpg','png','jpeg'))
```
to
```
if link['href'].endswith(('jpg','png','jpeg','bmp'))
```

**Comment by hasan356** [comment]
i am working on it

**Comment by ananyo2012** [comment]
Great @hasan356 :+1: Ping us here or in the gitter channel if you need any help

**Comment by abhsag24** [comment]
@hasan356 can't see the PR, are you sure you made it?
