### ISSUE TITLE
Delete wallpapers when they get too old 

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#5]
We should delete wallpapers when they get too old,  and also put a limit on the number of pics, in the pics directory

**Comment by pandusonu2** [comment]
Aint this issue closed along with #30 ?

**Comment by abhsag24** [comment]
yes the implentation in #30 is better closing this

**Comment by nemaniarjun** [comment]
Close this then?

**Comment by abhsag24** [comment]
hmm we still do want immediate delete well that makes this a dupe anyway
