### ISSUE TITLE
Exit UIP cleanly with ctrl + C

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#59]
So right now pressing ctrl - c during execution gives a very ugly traceback: This should be avoided.

hint : put call to scheduler in UIP.py in a try except block with `KeynoardInterrupt` as exception then use sys.exit(0)

**Comment by nkprince007** [comment]
@abhsag24  should the script exit with no Traceback at all, even when it is in scheduler.py, or just when it is still excuting in UIP.py?
