### ISSUE TITLE
add setup.py and setup UIP for linux and mac.

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#61]
for Windows we need py2exe and we'll add that our repo seperately after each release

**Comment by nkprince007** [comment]
Could this issue be addressed by using python setuptools and pip? 🤔

**Comment by abhsag24** [comment]
Absolutely :D
Also see docutils

**Comment by abhsag24** [comment]
@nkprince007  assigning you to this issue, tell me if you want to get unassigned

**Comment by nkprince007** [comment]
No, no, I'm interested in working on this.

**Comment by nkprince007** [comment]
To set this up, we need to use wheel, which inherently needs bundling in both python2 and python3. So we'll open an issue that addresses this and make the project compatible with both python 2 and 3.

**Comment by abhsag24** [comment]
@nkprince007 can you point to the documentation and why we need wheel exactly?

**Comment by nkprince007** [comment]
Universal wheels are shown [here](https://packaging.python.org/distributing/). As suggested by PyPI

**Comment by nkprince007** [comment]
But as suggested [here](https://www.digitalocean.com/community/tutorials/how-to-package-and-distribute-python-applications) we could use distutils too. What would you suggest bro? Universal packaging or just for python3?

**Comment by abhsag24** [comment]
@nkprince007 i suggest staying with python3 that's simpler

**Comment by abhsag24** [comment]
also we need to do this https://github.com/NIT-dgp/UIP/issues/74 before continuing right?

**Comment by abhsag24** [comment]
@nkprince007 can you join us on gitter?
