### ISSUE TITLE
Use arguments instead of raw input to start in offline mode

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#64]
For example to go into the offline mode a person should 
do: `python3 UIP.py --offline`

**Comment by abhsag24** [comment]
hint: use sys.argv :P

**Comment by abhsag24** [comment]
@DarkSouL11 can you do this since you've already worked on the file? it's kind of important?

**Comment by abhsag24** [comment]
i'm assigning tell me to unassign if you dont feel like doing this

**Comment by DarkSouL11** [comment]
I will do it :)
So I have to remove the option to go offline from raw_input?  or have both ?

**Comment by abhsag24** [comment]
remove the option from `input`

**Comment by DarkSouL11** [comment]
ok :thumbsup:
