### ISSUE TITLE
Add more Screenshots to Readme

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#73]
atleast 1 from windows and 1 from mac
@nkprince007 can you post the Mac screenshot here?

**Comment by abhsag24** [comment]
blocked till we can collect atleast 1 mac and 1 windows wallpaper

**Comment by abhsag24** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/8532031/20399321/947db578-ad16-11e6-93d9-5bd6af81ed1d.png)

example for the windows wallpaper

**Comment by nkprince007** [comment]
**example for mac wallpaper**

![5fb5cdba-ac6e-11e6-91d8-08e8bf0e6c57](https://cloud.githubusercontent.com/assets/17202890/20401710/eaf5f768-ad1f-11e6-9d34-ddf39149fca6.png)

**Comment by nkprince007** [comment]
I think, the block on this issue could be removed.. and fix could be applied in the readme section
