### ISSUE TITLE
organise code into folders

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#74]
let's use the structure:
```
UIP
|
  \uiplib\
     |
     \setWallpaper.py
     \scheduler.py
     \scrape.py
     \constants.py
  \tests\
     |
     \(empty for now or we can have place holder files)
|
|.gitignore
|requirement files
|Readme
|Contributing
|UIP.py
```

**Comment by nkprince007** [comment]
test -I __pycache__
.
├── README.md
├── UIP.py
├── bears
│   ├── LineLengthBear.py
│   ├── PEP8Bear.py
│   └── SpaceConsistencyBear.py
├── examples
│   └── UIP_screenshot.png
├── mac-requirements.txt
├── pics
├── requirements.txt
├── tests
│   └── __init__.py
└── uiplib
    ├── constants.py
    ├── scheduler.py
    ├── scrape.py
    └── setWallpaper.py

5 directories, 13 files

Is this structure ok, bro?

**Comment by abhsag24** [comment]
yup this is awesome :D add the `__init__.py` to uiplib as well, and beware u'll have to fix all the imports :P

**Comment by nkprince007** [comment]
Ok, bro.. :+1:

**Comment by nkprince007** [comment]
Is this okay bro?

```
tree -I __pycache__
.
├── README.md
├── UIP.py
├── bears
│   ├── LineLengthBear.py
│   ├── PEP8Bear.py
│   └── SpaceConsistencyBear.py
├── constants.py
├── examples
│   └── UIP_screenshot.png
├── mac-requirements.txt
├── requirements.txt
├── tests
│   └── __init__.py
└── uiplib
    ├── __init__.py
    ├── constants.py
    ├── scheduler.py
    ├── scrape.py
    └── setWallpaper.py

4 directories, 15 files
```
