### ISSUE TITLE
make the code universal (be it python2 or python3)

### ISSUE THREAD

**Issue by nkprince007** [NIT-dgp/UIP#75]
use import __future__ to address the changes and let python2 work with our package.

**Comment by abhsag24** [comment]
we use bs4 that doesnt work with python2 right?

**Comment by nkprince007** [comment]
Is it? But it says [here](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) that it works on python2.7 and python3.4 alike.

**Comment by abhsag24** [comment]
ahh nice :D also on linux we use python3-gi :( ? which is python-gobject both have different import methods

**Comment by abhsag24** [comment]
do we really need wheels? wheels is just a feature right? we dont **need** it :P

**Comment by nkprince007** [comment]
yeah, we don't need it I guess. This just makes it way more complex to package. We'll go for distutils instead.

**Comment by abhsag24** [comment]
yes py2exe works with distutils as well :P

**Comment by nkprince007** [comment]
Ok, then, I'm closing the issue here.
