### ISSUE TITLE
stop showing random numbers on exit

### ISSUE THREAD

**Issue by nkprince007** [NIT-dgp/UIP#77]
The below clip showcases the issue, as the user presses Ctrl+C, the script shows a random number before exit.

![screen shot 2016-11-18 at 4 00 21 am](https://cloud.githubusercontent.com/assets/17202890/20413493/50cd701a-ad53-11e6-9138-9bb1cbcb203c.png)

**Comment by abhsag24** [comment]
code areas: 
1. https://github.com/NIT-dgp/UIP/blob/master/setWallpaper.py#L28 the print in windows desktop changer
2. https://github.com/NIT-dgp/UIP/blob/master/scheduler.py#L14 the `print(time.time())`
