### ISSUE TITLE
Add tests for all functions and modules

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#8]
Right now we don't test anything it'd be nice if we add tests to our code asap

**Comment by nemaniarjun** [comment]
What all is still left to be tested?

**Comment by abhsag24** [comment]
all of `scheduler, setWallpaper and most files except scrape` even `scrape` isn't 100% yet

**Comment by nemaniarjun** [comment]
We have Duplicates for all of them. (AFAIK)
Close this?

**Comment by nkprince007** [comment]
I'll work on this. :smile:
