### ISSUE TITLE
Not all images are downloaded

### ISSUE THREAD

**Issue by mayank1495** [NIT-dgp/UIP#88]
The script downloads image only from the first page in which only few "hrefs" end in "jpg,png..etc". Hence out of the first 25 links only around 4-5 images are downloaded.

**Comment by abhsag24** [comment]
can you type in the steps to reproduce this?

**Comment by abhsag24** [comment]
currently we get the full 15 images that are to be downloaded

**Comment by abhsag24** [comment]
yes checed reddit.com/r/wallpapers those tyes of posts have just started coming in

**Comment by abhsag24** [comment]
i guess instead of collecting 15 links we collect all links till we get 15 with suitable extensions

**Comment by mayank1495** [comment]
I am windows.
1. While in project folder i run in cmd: `py -3 UIP.py`
2.It started downloading and then showed changing wallpaper to <path name>
3.Now when i checked my pics folder it had 4 images.
4.I renamed it to pic2. Repeated the process it again had 4 images.
![capture](https://cloud.githubusercontent.com/assets/14853345/20441952/9e6f8ac6-adec-11e6-8393-f86c268a10f7.JPG)

**Comment by mayank1495** [comment]
Yeah right. We need to run it till we get the number of images we want.
