### ISSUE TITLE
Shortcut to change wallpaper without waiting for timeout

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#89]
I want a shortcut to change the wallpaper before timeout.
I might not like a currently set random wallpaper. I would like to have an option to change it rather than wait for the timespan.

**Comment by mayank1495** [comment]
Can you tell whats the current timespan @pandusonu2 ? Windows seems to have another problem.

**Comment by pandusonu2** [comment]
Ah..... you set it in constants.py
