### ISSUE TITLE
Wallpaper not changing on windows

### ISSUE THREAD

**Issue by mayank1495** [NIT-dgp/UIP#90]
I changed the **TIMEOUT** from **"30*60" to "120"** which i guess would mean the wallpaper should change at an interval of 2mins.
But the wallpaper did not change at all. Instead every time i run the script, wallpaper changes but fails to change for the given interval.

![capture2](https://cloud.githubusercontent.com/assets/14853345/20442654/7fdcb0f4-adef-11e6-9949-c064929d0616.JPG)
![capture3](https://cloud.githubusercontent.com/assets/14853345/20442675/942a2d2a-adef-11e6-8161-3ebe1d19720a.JPG)

**Comment by nkprince007** [comment]
@mayank1495, TIMEOUT is specified in seconds, I guess.

**Comment by abhsag24** [comment]
hey so i did this and it changed for me :(

**Comment by abhsag24** [comment]
i'm on windows 10, 64 bit

**Comment by nemaniarjun** [comment]
Needs more info? Bumping this for @mayank1495.

@abhsag24 I don't know what the protocol is to close this one.

**Comment by nkprince007** [comment]
Is this issue still prevalent @abhsag24 ?

**Comment by abhsag24** [comment]
@nkprince007 it was never an issue for me :P
