### ISSUE TITLE
flag options for all settings

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#95]
also use `argparse` library for this.

**Comment by nkprince007** [comment]
@abhsag24 could you specify all the settings that need to be added as flags?

**Comment by abhsag24** [comment]
sure i'll list all settings even if they aren't on UIP at the moment :P

**Comment by nemaniarjun** [comment]
Any flags left?

**Comment by abhsag24** [comment]
--pics-folder

**Comment by nemaniarjun** [comment]
We have an issue for that. Close this?

**Comment by nemaniarjun** [comment]
Closing, deprecating CLI
